### ISSUE TITLE
Did Safari recently throttle postMessage?

### ISSUE THREAD

**Issue by sterpe** [YuzuJS/setImmediate#41]
On latest Safari 7.1.2 setImmediate sort @ http://jphpsf.github.io/setImmediate-shim-demo/
performs no better (and sometimes worse) than the 4ms setTimeout.  Chrome & Firefox seem 
unaffected.  

Does anyone know if Apple throttled their postMessage implementation down to 4ms?

**Comment by sterpe** [comment]
Filed a bug report with Apple.

**Comment by domenic** [comment]
I don't have a Mac to test this with, but interesting find if so. Someone with a Mac could help investigate which mechanisms have been throttled and we could update the polyfill to work around this.

**Comment by gaearon** [comment]
Can this be of any help?

https://github.com/petkaantonov/bluebird/blob/master/src/schedule.js

I think Bluebird's using `MutationObserver` on client for `setImmediate`..

**Comment by domenic** [comment]
@gaearon no, please see https://github.com/YuzuJS/setImmediate#macrotasks-and-microtasks

**Comment by gaearon** [comment]
Thank you! I should've read it first.

**Comment by fdecampredon** [comment]
Apparently postMessage is indeed throttled simple test show a delay of 3 or 4ms; 
```javascript
var t;
window.onmessage = function () { console.log(Date.now() - t); }
function message() { t = Date.now(); window.postMessage(null, '*'); }
message() // log 3 or 4
```
Same goes for message channel (just in case), I don't know if we have other option here :/.

**Comment by domenic** [comment]
I was wondering about MessageChannel. What about the `<script>` onreadystatechange?

**Comment by fdecampredon** [comment]
```
"onreadystatechange" in document.createElement("script") // false
```

**Comment by domenic** [comment]
Arggh. I am not sure what to do now :-/.

**Comment by malyw** [comment]
I provided [Codepen example](http://codepen.io/malyw/pen/XJRqLe) with the test of **postMessage**/**messageChannel**/**setTimeout** ways of providing **setImmediate**.
The test is at the bottom of JS:
```javascript
// -------- TEST --------

  // ({}.toString.call(window.process) === "[object process]") => false (in Safari 8.0.2)
  // installNextTickImplementation => skipped

  // canUsePostMessage() => true (in Safari 8.0.2)
  window.postMessageSetImmediate = installPostMessageImplementation();
  window.postMessageSetImmediate._name = 'postMessageSetImmediate';

  // window.MessageChannel => MessageChannelConstructor (in Safari 8.0.2)
  window.messageChannelSetImmediate = installMessageChannelImplementation();
  window.messageChannelSetImmediate._name = 'messageChannelSetImmediate';

  // "onreadystatechange" in document.createElement("script") => false (in Safari 8.0.2)
  // installReadyStateChangeImplementation => skipped

  // TIMEOUT
  window.setTimeoutSetImmediate = installSetTimeoutImplementation();
  window.setTimeoutSetImmediate._name = 'setTimeoutSetImmediate';

  // TEST
  function test(method, callback) {
    var startedTime = Date.now();
    var numberOfTests = 10000;
    var testsToBeDone = numberOfTests;
    var outputResults = function () {
      console.log('"' + method._name + '" takes in average: ' +
      (Date.now() - startedTime) / numberOfTests +
      ' ms (' + numberOfTests + ' tests)');

      callback && callback();
    };
    var runTest = function () {
      testsToBeDone--;
      if (testsToBeDone) {
        method(runTest);
      } else {
        outputResults();
      }
    };
    runTest();
  }

  test(postMessageSetImmediate, function () {
    test(messageChannelSetImmediate, function () {
      test(setTimeoutSetImmediate);
    });
  });
```

Results for OS X Yosemite 10.10.1
Safari 8.0.2 (10600.2.5):
>> "postMessageSetImmediate" takes in average: 0.0319 ms (10000 tests)
>> "messageChannelSetImmediate" takes in average: 0.0026 ms (10000 tests)
>> "setTimeoutSetImmediate" takes in average: 5.1198 ms (10000 tests)
Chrome Canary 42.0.2281.0 canary (64-bit):
>> "postMessageSetImmediate" takes in average: 0.0941 ms (10000 tests)
>> "messageChannelSetImmediate" takes in average: 0.0662 ms (10000 tests)
>> "setTimeoutSetImmediate" takes in average: 5.0065 ms (10000 tests)

You can use [Codepen cross browsers testing feature](http://blog.codepen.io/2014/12/15/test-pens-browser-live-free-crossbrowsertesting-com/) to test that/your codepen code on OS X.

So on both browsers **MessageChannel** method is faster than **postMessage**.

**Comment by sterpe** [comment]
Okay glad it's not just me.  Curious if anyone has any insight into why Aplle did this?

**Comment by fdecampredon** [comment]
no it's just not you I didn't do the Yosemite maj, and with osx 10.9.5 safari 7.1.2 there is a problem. I'm glad this has been fixed with the ulterior safari version.

**Comment by domenic** [comment]
Oh I see, so this is old Safari's problem, but new Safari is OK. In that case there is no issue!
