### ISSUE TITLE
How about requestIdleCallback?

### ISSUE THREAD

**Issue by jimmywarting** [YuzuJS/setImmediate#53]
Currently in chrome 47 (beta atm)

- Could it be used? 
- Is it faster?
- Is it better?
- Is it slower?
- Advantages / Disadvantage?

**Comment by domenic** [comment]
It has entirely different semantics, unrelated to setImmediate...

**Comment by jimmywarting** [comment]
Hm,  ok. 
Wonder what the differences is...
